# Generated by Django 6.0.4 on 2026-05-11 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_avance', models.CharField(choices=[('AID', 'Avance Aïd'), ('RENTREE', 'Avance Rentrée Scolaire'), ('PREAMENAGEMENT', 'Avance Pré-aménagement')], max_length=20, verbose_name="Type d'avance")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('FERME', 'Fermé')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut', 'ACTIF')), fields=('type_avance', 'annee'), name='unique_event_actif_par_type_annee')],
            },
        ),
    ]
