# Generated by Django 5.0.6 on 2026-05-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_debut']},
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_event_actif_par_type_annee',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='annee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('FERME', 'Fermé')], default='ACTIF', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='type_avance',
            field=models.CharField(choices=[('AID', 'Avance Aïd'), ('RENTREE', 'Avance Rentrée Scolaire'), ('PREAMENAGEMENT', 'Avance Pré-aménagement')], max_length=20),
        ),
    ]
