# Generated by Django 5.0.6 on 2026-05-14 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionlog',
            options={'ordering': ['-date_heure']},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utilisateur'},
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='type_action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('SAISIE', 'Saisie demande'), ('EVENT_CREATE', 'Création événement'), ('EVENT_EDIT', 'Modification événement'), ('EXPORT', 'Export données'), ('ACCOUNT_CREATE', 'Création compte'), ('ACCOUNT_TOGGLE', 'Activation/Désactivation'), ('AGENT_ADD', 'Ajout agent')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('AGENT_AJOUTE', 'Nouvel agent ajouté'), ('COMPTE_CREE', 'Compte créé'), ('EVENT_OUVERT', 'Événement ouvert'), ('EVENT_FERME', 'Événement fermé')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
