# Generated by Django 6.0.4 on 2026-05-11 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('INCLUS', 'Inclus'), ('EXCLUS', 'Exclus')], max_length=10)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='agents.agent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='events.event')),
                ('gestionnaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
                'ordering': ['-date_saisie'],
                'constraints': [models.UniqueConstraint(fields=('agent', 'event'), name='unique_agent_par_event')],
            },
        ),
    ]
