# Generated by Django 5.0.6 on 2026-05-14 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_options_agent_ajoute_par_and_more'),
        ('demandes', '0001_initial'),
        ('events', '0002_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demande',
            options={'ordering': ['-date_saisie']},
        ),
        migrations.RemoveConstraint(
            model_name='demande',
            name='unique_agent_par_event',
        ),
        migrations.AddConstraint(
            model_name='demande',
            constraint=models.UniqueConstraint(fields=('agent', 'event'), name='unique_agent_event'),
        ),
    ]
